config/routes.rb
CapDesign::Application.routes.draw do
  resources :provinces

  resources :categories

  get "shop/new"

  get "shop/create"

  resources :accounts

  resources :customers

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :products

  match "/" => "shop#index"
  match 'about' => "about#about"
  match 'contact' => "about#contact"

end

app/models/about.rb
class About < ActiveRecord::Base
  attr_accessible :about, :contact
end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessible :acc_ID, :email, :password, :salt
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :cat_id, :description, :name
  has_many :products
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :cust_ID, :address, :first_name, :last_name, :phonenumber
  belongs_to :province
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :available, :description, :name, :price, :prod_id, :image_file_name, :image_content_type, :image_file_size, :image_updated_at, :sale, :saleprice, :new
  has_attached_file :image, :style => { :medium => "1000x1000>", :thumb => "500x500>"}
  validates :name,:price,:description, :presence => true
  belongs_to :category
end

app/models/province.rb
class Province < ActiveRecord::Base
  attr_accessible :GST_tax, :HST_tax, :PST_tax, :QST_tax, :prov_id, :province
  validates :province, :presence => true
  has_many :customers
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def about

      @about = About.all

      respond_to do |format|
        format.html # about.html.erb
        format.json { render json: @about }
      end

  end

  def contact

    @about = About.all
    respond_to do |format|
      format.html # contact.html.erb
      format.json { render json: @about }
    end
  end

end

app/controllers/accounts_controller.rb
class AccountsController < InheritedResources::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
end

app/controllers/customers_controller.rb
class CustomersController < InheritedResources::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/provinces_controller.rb
class ProvincesController < InheritedResources::Base
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/about/about.html.erb
<p id="notice"><%= notice %></p>
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <title>Welcome to Foundation | Banded</title>

  <!-- Included CSS Files (Uncompressed) -->
  <!--
  <link rel="stylesheet" href="stylesheets/foundation.css">
  -->

  <!-- Included CSS Files (Compressed) -->
  <link rel="stylesheet" href="stylesheets/foundation.min.css">
  <link rel="stylesheet" href="stylesheets/app.css">

  <script src="javascripts/modernizr.foundation.js"></script>
</head>
<body>
<div class="row">
  <div class="twelve columns">

    <!-- Navigation -->

    <div class="row">
      <div class="twelve columns">

        <ul class="top-bar">

          <ul>
            <li class="name"><h1><a href="#">Title</a></h1></li>
            <li class="toggle-topbar"><a href="#"></a></li>
          </ul>

          <section>
            <ul class="left">
              <li><a href="/">Home</a></li>
              <li><a href="/about">About</a></li>
              <li><a href="/contact">Contacts</a></li>
            </ul>


          </section>

      </div>
    </div>

    <!-- End Navigation -->

    <div class="row">

      <div class="twelve columns">

        <h1>About Us</h1>
        <p>
          <% @about.each do |abouts| %>
              <%=	 abouts.about %>
          <% end %>
        </p>

        <%=	link_to "Back to Home Page" , '/'  %>
      </div>
    </div>


    <!-- Footer -->

    <footer class="row">
      <div class="twelve columns"><hr />
        <div class="row">

          <div class="six columns">
            <p>&copy; Copyright no one at all. Go to town.</p>
          </div>

          <div class="six columns">
            <ul class="link-list right">
              <li><a href="#">Link 1</a></li>
              <li><a href="#">Link 2</a></li>
              <li><a href="#">Link 3</a></li>
              <li><a href="#">Link 4</a></li>
            </ul>
          </div>

        </div>
      </div>
    </footer>

    <!-- End Footer -->

  </div>
</div>

<!-- Included JS Files (Uncompressed) -->
<!--

<script src="javascripts/jquery.js"></script>

<script src="javascripts/jquery.foundation.mediaQueryToggle.js"></script>

<script src="javascripts/jquery.foundation.forms.js"></script>

<script src="javascripts/jquery.foundation.reveal.js"></script>

<script src="javascripts/jquery.foundation.orbit.js"></script>

<script src="javascripts/jquery.foundation.navigation.js"></script>

<script src="javascripts/jquery.foundation.buttons.js"></script>

<script src="javascripts/jquery.foundation.tabs.js"></script>

<script src="javascripts/jquery.foundation.tooltips.js"></script>

<script src="javascripts/jquery.foundation.accordion.js"></script>

<script src="javascripts/jquery.placeholder.js"></script>

<script src="javascripts/jquery.foundation.alerts.js"></script>

<script src="javascripts/jquery.foundation.topbar.js"></script>

<script src="javascripts/jquery.foundation.joyride.js"></script>

<script src="javascripts/jquery.foundation.clearing.js"></script>

<script src="javascripts/jquery.foundation.magellan.js"></script>

-->

<!-- Included JS Files (Compressed) -->
<script src="javascripts/jquery.js"></script>
<script src="javascripts/foundation.min.js"></script>

<!-- Initialize JS Plugins -->
<script src="javascripts/app.js"></script>
</body>
</html>

app/views/about/contact.html.erb
<p id="notice"><%= notice %></p>
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <title>Welcome to Foundation | Banded</title>

  <!-- Included CSS Files (Uncompressed) -->
  <!--
  <link rel="stylesheet" href="stylesheets/foundation.css">
  -->

  <!-- Included CSS Files (Compressed) -->
  <link rel="stylesheet" href="stylesheets/foundation.min.css">
  <link rel="stylesheet" href="stylesheets/app.css">

  <script src="javascripts/modernizr.foundation.js"></script>
</head>
<body>
<div class="row">
  <div class="twelve columns">

    <!-- Navigation -->

    <div class="row">
      <div class="twelve columns">

        <ul class="top-bar">

          <ul>
            <li class="name"><h1><a href="#">Title</a></h1></li>
            <li class="toggle-topbar"><a href="#"></a></li>
          </ul>

          <section>
            <ul class="left">
              <li><a href="/">Home</a></li>
              <li><a href="/about">About</a></li>
              <li><a href="/contact">Contacts</a></li>
            </ul>


          </section>

      </div>
    </div>

    <!-- End Navigation -->

    <div class="row">

      <div class="twelve columns">

        <h1>Contact Us</h1>
        <% @about.each do |abouts| %>
            <%=	 abouts.contact %>
        <% end %>

        <%=	link_to "Back to Home Page" , '/'  %>
      </div>
    </div>


    <!-- Footer -->

    <footer class="row">
      <div class="twelve columns"><hr />
        <div class="row">

          <div class="six columns">
            <p>&copy; Copyright no one at all. Go to town.</p>
          </div>

          <div class="six columns">
            <ul class="link-list right">
              <li><a href="#">Link 1</a></li>
              <li><a href="#">Link 2</a></li>
              <li><a href="#">Link 3</a></li>
              <li><a href="#">Link 4</a></li>
            </ul>
          </div>

        </div>
      </div>
    </footer>

    <!-- End Footer -->

  </div>
</div>

<!-- Included JS Files (Uncompressed) -->
<!--

<script src="javascripts/jquery.js"></script>

<script src="javascripts/jquery.foundation.mediaQueryToggle.js"></script>

<script src="javascripts/jquery.foundation.forms.js"></script>

<script src="javascripts/jquery.foundation.reveal.js"></script>

<script src="javascripts/jquery.foundation.orbit.js"></script>

<script src="javascripts/jquery.foundation.navigation.js"></script>

<script src="javascripts/jquery.foundation.buttons.js"></script>

<script src="javascripts/jquery.foundation.tabs.js"></script>

<script src="javascripts/jquery.foundation.tooltips.js"></script>

<script src="javascripts/jquery.foundation.accordion.js"></script>

<script src="javascripts/jquery.placeholder.js"></script>

<script src="javascripts/jquery.foundation.alerts.js"></script>

<script src="javascripts/jquery.foundation.topbar.js"></script>

<script src="javascripts/jquery.foundation.joyride.js"></script>

<script src="javascripts/jquery.foundation.clearing.js"></script>

<script src="javascripts/jquery.foundation.magellan.js"></script>

-->

<!-- Included JS Files (Compressed) -->
<script src="javascripts/jquery.js"></script>
<script src="javascripts/foundation.min.js"></script>

<!-- Initialize JS Plugins -->
<script src="javascripts/app.js"></script>
</body>
</html>

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :salt %><br />
    <%= f.text_field :salt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Password</th>
    <th>Salt</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.acc_ID %></td>
    <td><%= account.email %></td>
    <td><%= account.password %></td>
    <td><%= account.salt %></td>
    <td><%= link_to 'Show', account %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Acc id:</b>
  <%= @account.acc_ID %>
</p>

<p>
  <b>Email:</b>
  <%= @account.email %>
</p>

<p>
  <b>Password:</b>
  <%= @account.password %>
</p>

<p>
  <b>Salt:</b>
  <%= @account.salt %>
</p>


<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cat_id %><br />
    <%= f.number_field :cat_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Cat</th>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.cat_id %></td>
    <td><%= category.name %></td>
    <td><%= category.description %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cat:</b>
  <%= @category.cat_id %>
</p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Description:</b>
  <%= @category.description %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phonenumber %><br />
    <%= f.text_field :phonenumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Address</th>
    <th>Phonenumber</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.first_name %></td>
    <td><%= customer.last_name %></td>
    <td><%= customer.address %></td>
    <td><%= customer.phonenumber %></td>
    <td><%= link_to 'Show', customer %></td>
    <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
    <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @customer.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @customer.last_name %>
</p>

<p>
  <b>Address:</b>
  <%= @customer.address %>
</p>

<p>
  <b>Phonenumber:</b>
  <%= @customer.phonenumber %>
</p>


<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :prod_id %><br />
    <%= f.number_field :prod_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :available %><br />
    <%= f.check_box :available %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Captivating Design</h1>
<%= link_to "Admin Page", "/admin/login"	 %>
<table>
  <tr>
    <th>Prod</th>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Available</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.prod_id %></td>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.price %></td>
    <td><%= product.available %></td>
  </tr>
<% end %>
</table>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Prod:</b>
  <%= @product.prod_id %>
</p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Available:</b>
  <%= @product.available %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/provinces/_form.html.erb
<%= form_for(@province) do |f| %>
  <% if @province.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@province.errors.count, "error") %> prohibited this province from being saved:</h2>

      <ul>
      <% @province.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :prov_id %><br />
    <%= f.number_field :prov_id %>
  </div>
  <div class="field">
    <%= f.label :province %><br />
    <%= f.text_field :province %>
  </div>
  <div class="field">
    <%= f.label :PST_tax %><br />
    <%= f.text_field :PST_tax %>
  </div>
  <div class="field">
    <%= f.label :GST_tax %><br />
    <%= f.text_field :GST_tax %>
  </div>
  <div class="field">
    <%= f.label :QST_tax %><br />
    <%= f.text_field :QST_tax %>
  </div>
  <div class="field">
    <%= f.label :HST_tax %><br />
    <%= f.text_field :HST_tax %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/provinces/edit.html.erb
<h1>Editing province</h1>

<%= render 'form' %>

<%= link_to 'Show', @province %> |
<%= link_to 'Back', provinces_path %>

app/views/provinces/index.html.erb
<h1>Listing provinces</h1>

<table>
  <tr>
    <th>Prov</th>
    <th>Province</th>
    <th>Pst tax</th>
    <th>Gst tax</th>
    <th>Qst tax</th>
    <th>Hst tax</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @provinces.each do |province| %>
  <tr>
    <td><%= province.prov_id %></td>
    <td><%= province.province %></td>
    <td><%= province.PST_tax %></td>
    <td><%= province.GST_tax %></td>
    <td><%= province.QST_tax %></td>
    <td><%= province.HST_tax %></td>
    <td><%= link_to 'Show', province %></td>
    <td><%= link_to 'Edit', edit_province_path(province) %></td>
    <td><%= link_to 'Destroy', province, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Province', new_province_path %>

app/views/provinces/new.html.erb
<h1>New province</h1>

<%= render 'form' %>

<%= link_to 'Back', provinces_path %>

app/views/provinces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Prov:</b>
  <%= @province.prov_id %>
</p>

<p>
  <b>Province:</b>
  <%= @province.province %>
</p>

<p>
  <b>Pst tax:</b>
  <%= @province.PST_tax %>
</p>

<p>
  <b>Gst tax:</b>
  <%= @province.GST_tax %>
</p>

<p>
  <b>Qst tax:</b>
  <%= @province.QST_tax %>
</p>

<p>
  <b>Hst tax:</b>
  <%= @province.HST_tax %>
</p>


<%= link_to 'Edit', edit_province_path(@province) %> |
<%= link_to 'Back', provinces_path %>